### ISSUE TITLE
False flags when not logged into RedCap

### ISSUE THREAD

**Issue by higaldy** [tertek/redcap-unique-actiontag#12]
We had false unique tag pickups when users completing surveys were not logged into RedCap

**Comment by tertek** [comment]
If I understand you correctly, the UNIQUE tag did not work on the Survey Page for users that are not logged in to REDCap correct?
Can you please share one or two screenshots documenting the tag usage?

**Comment by tertek** [comment]
It seems like this issue appears as soon as table-based authentication is enabled in REDCap. I could not reproduce on my local development environment since it was without authentication. Now that several other users have reported this issue I have realized what I was missing. Sorry for that!

It seems like that without being logged-in the request from within the input field to the back-end gets blocked (which should be expected for security reasons). I will try to find a way to allow requests using CSRF and piggy-backing the session somehow.

**Comment by tertek** [comment]
Unfortunately, it is not easily possible to change the access from external without having medium security trade-off. I currently do not have the time to make a solid implementation and therefore dropping support for survey page mode in next version.

If anyone wants to add support for Survey Page please open a PR.

**Comment by tertek** [comment]
Support for Survey Page dropped in Release Version 1.2.7.
